
version: "3.5"

volumes:
     app-volume:

networks:
  specify:
    driver: bridge

services:
  webportal:
    build:
      context: ./
      dockerfile: Dockerfile
    networks:
      - specify
    restart: always
    volumes:
      - app-volume:/home/specify


  web:
    image: nginx
    networks:
      - specify
    restart: always
    ports:
      - '8080:80'
    volumes:
      - ./webportal-nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - app-volume:/home/specify
    depends_on:
      - webportal
